### PR TITLE
Backend/feed

### PR DESCRIPTION
**Pull request by JThanat**
This PR is partial implementation of #127 #164. There are two new APIs available and one change in URL name.
- API for similar market at the bottom of landing page can be accessed via (`/api/similar-market`). This will return 4 related markets. However, it is just a random for now. 

- API for categorized feed can be access using `/api/market-feed`. It will return data like 
```
{
    "recommend_market": [
        {
            "id": 16,
            ...
        },
    "category2_market" : [...]
}
```
- API for search market was changed from `/api/market-feed` to `/api/market-search`

### CODE REVIEW

**Comment by futurizing** [comment]
@JThanat Because it's in the UI mock, can you add a field for each recommended market that count how many vendors have been reserved to date?

**Comment by JThanat** [comment]
@sirinthra-cc Please check the search result

**Comment by JThanat** [comment]
@futurizing Search query (e.g. http://localhost:8000/market-search/?search=fin%20market) should return 0 markets

**Comment by JThanat** [comment]
@futurizing Please check if the result is okay for now

**Pull request merged**
